name: Auto Push

on:
  push:
    branches:
      - main

jobs:
  auto-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Git
      run: |
        git config --global user.name "Privateclublive"
        git config --global user.email "alecfasani@mac.com"

    - name: Run auto-push script
      run: ./auto-push.sh